# Generated by Django 4.0.4 on 2024-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_theme_color_theme_first_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='badge_color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
