# Generated by Django 4.0.4 on 2024-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_intervention_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tab_background_color',
            field=models.CharField(default='#DBEAF2', max_length=7),
            preserve_default=False,
        ),
    ]
