# Generated by Django 4.0.4 on 2024-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_theme_tab_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='public_theme',
            field=models.BooleanField(default=False),
        ),
    ]
