# Generated by Django 4.0.4 on 2024-05-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='farmer_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/', verbose_name='profile image'),
        ),
    ]
