# Generated by Django 4.0.4 on 2024-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0002_alter_company_image_alter_farmer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sso_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
