# Generated by Django 4.0.4 on 2024-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0003_company_sso_id_user_sso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='batches', to='supply_chains.farmer'),
        ),
    ]
