# Generated by Django 4.0.4 on 2024-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0004_alter_batch_farmers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='supply_chains',
            field=models.ManyToManyField(blank=True, related_name='farmers', to='supply_chains.supplychain'),
        ),
    ]
