# Generated by Django 4.0.4 on 2024-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chains', '0006_alter_batch_supply_chain_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='company_images'),
        ),
    ]
