# Generated by Django 4.0.4 on 2024-12-19 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_yearlytreecoverloss_delete_deforestationsummary'),
        ('supply_chains', '0007_alter_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisQueue',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('status', models.IntegerField(choices=[(1, 'Started'), (2, 'Failed'), (3, 'In Queue'), (4, 'Completed')], default=3)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_queue', to='farms.farm')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
