# Generated by Django 4.0.4 on 2024-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='geo_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
