# Generated by Django 4.0.4 on 2024-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_geo_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_type',
            field=models.CharField(choices=[('POINT', 'Point'), ('POLYGON', 'Polygon')], max_length=255),
        ),
    ]
