# Generated by Django 4.0.4 on 2024-05-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_farm_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='latlong',
        ),
    ]
