# Generated by Django 4.0.4 on 2024-12-10 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0005_remove_farm_farm_type_remove_farm_latlong'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyTreeCoverLoss',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('year', models.IntegerField(default=2014)),
                ('canopy_density', models.FloatField(default=30)),
                ('value', models.FloatField(default=0.0)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_tree_cover_losses', to='farms.farm')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_%(class)s_objects', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DeforestationSummary',
        ),
    ]
